name: Build on Ubuntu
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare directory structure
        run: |
          mkdir x6100
      - name: Checkout Buildroot
        uses: actions/checkout@v4
        with:
          repository: gdyuldin/AetherX6100Buildroot
          path: x6100/AetherX6100Buildroot
      - name: Checkout GUI
        uses: actions/checkout@v4
        with:
          repository: gdyuldin/x6100_gui
          path: x6100/x6100_gui