name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare directory structure
        run: mkdir x6100
      - name: Checkout Buildroot
        uses: actions/checkout@v4
        with:
          repository: gdyuldin/AetherX6100Buildroot
          path: x6100/AetherX6100Buildroot
      - name: Checkout GUI
        uses: actions/checkout@v4
        with:
          repository: gdyuldin/x6100_gui
          path: x6100/x6100_gui
      - name: Cache Buildroot build directory
        id: cache-buildroot
        uses: actions/cache@v3
        with:
          key: buildroot-cache
          path: x6100/AetherX6100Buildroot/build
      # - name: Cache GUI build directory
      #   id: cache-gui
      #   uses: actions/cache@v3
      #   with:
      #     key: gui-cache
      #     path: x6100/x6100_gui/buildroot/build
      - name: Install required packages
        env:
          LANG: en_US.UTF-8
        run: |
        
          sudo apt-get update 
          sudo apt-get upgrade -y
          sudo apt-get install -y locales
          sudo localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
          sudo apt-get install -y git build-essential wget cpio unzip rsync bc libncurses5 libncurses5-dev libncursesw5-dev libxkbfile1 libxkbfile-dev libxkbcommon0 libxkbcommon-x11-dev libxkbcommon-x11-0 libxkbcommon-dev libxkbcommon-tools libxkbregistry-dev libxkbregistry0 screen file cmake python3 python3-dev python3-setuptools python3-pip
      - if: ${{ steps.cache-buildroot.outputs.cache-hit != 'true' }}
        working-directory: x6100/AetherX6100Buildroot
        name: Compile buildroot
        run: bash ./br_build.sh
      - name: 'Upload buildroot image'
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-image
          path: x6100/AetherX6100Buildroot/build/images/sdcard.img
      - working-directory: x6100/x6100_gui
        name: Compile GUI
        run: |
          git submodule init
          git submodule update
          cd buildroot
          ./build.sh
      - name: Archive GUI artifact files
        run: tar -czf gui.tar.gz x6100/x6100_gui
      - name: 'Upload GUI archive'
        uses: actions/upload-artifact@v4
        with:
          name: gui-archive
          path: gui.tar.gz

